project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ 115a"
  favicon: "plot/econ115a-hex-logo.png"
  
  repo-url: https://github.com/Econ-115a-Econometrics/econ115a-site
  site-url: https://econ-115a-econometrics.github.io/econ115a-site/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ115a-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "m1-intro-stat.qmd"
            text: "Module 1: Introduction to Statistical Methods"
          - href: "m2-eda.qmd"
            text: "Module 2: Exploratory data analysis (EDA)"
          - href: "m3-exploring-assumptions.qmd"
            text: "Module 3: Exploring assumptions"
          - href: "m4-correlation.qmd"
            text: "Module 4: Correlation analysis"
          - href: "m5-regression.qmd"
            text: "Module 5: Regression analysis"
          - href: "m6-logistic.qmd"
            text: "Module 6: Logistic regression"
          - href: "m7-test-means.qmd"
            text: "Module 7: Tests on Means"
          - href: "m8-non-parametric.qmd"
            text: "Module 8: Non-parametric tests"
          - href: "m9-efa.qmd"
            text: "Module 9: Exploratory Factor Analysis (EFA)"



format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual
