project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ 115a"
  favicon: "plot/econ115a-hex-logo.png"
  
  repo-url: https://github.com/Econ-115a-Econometrics/econ115a-site
  site-url: https://econ-115a-econometrics.github.io/econ115a-site/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ115a-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "m1-intro-stat.qmd"
            text: "Module 1: Introduction to Statistical Methods"
          - href: "m2-survey-design.qmd"
            text: "Module 2: Survey Research Design"
          - href: ""
            text: "Module 3: Exploratory data analysis (EDA)"
          - href: ""
            text: "Module 4: Exploring assumptions"
          - href: ""
            text: "Module 5: Correlation analysis"
          - href: ""
            text: "Module 6: Regression analysis"
          - href: ""
            text: "Module 7: Logistic regression"
          - href: ""
            text: "Module 8: Tests on Means"
          - href: ""
            text: "Module 9: Non-parametric tests"
          - href: ""
            text: "Module 10: Exploratory Factor Analysis (EFA)"
      - section: "Midterm & Final projects"
        contents:
          - href: "term-01-midterm-project.qmd"
            text: "Midterm project: Research concept note"



format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual
